:                                                           --DML OPERATIONS FOR SKYBARREL AT UNION BANK--

-- I CREATED A DATABASE

CREATE DATABASE SkyBarrel_UB;

-- I CREATED THE EMPLOYEES TABLE

CREATE TABLE EMPLOYEES
(
 EmployeeID INT NOT NULL,
 FirstName VARCHAR (50) NOT NULL,
 LastName VARCHAR (50) NOT NULL,
 DepartmentID  INT NOT NULL,
 Position VARCHAR (50) NOT NULL,
 Salary DECIMAL (10,2) NOT NULL,
 );

 -- EMPLOYEEID AS THE UNIQUE IDENTIFIER IN THE TABLE

 ALTER TABLE EMPLOYEES
 ADD CONSTRAINT PK_EMPLOYEE_EMPLOYEEID_ PRIMARY KEY (EmployeeID);

 -- DEPARTMENTID IN THE EMPLOYEES TABLE REFERENCING DEPARTMENTID IN THE DEPARTMENT TABLE (FOREIGN KEY)

 ALTER TABLE EMPLOYEES
 ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENTID6 FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT (DEPARTMENTID);

 -- ALTERING TABLE TO ADD A NEW COLUMN TO IT

 ALTER TABLE EMPLOYEES
 ADD PERFORMANCE_BONUS NUMERIC (10,2) NULL;

 -- INSERTING RECORDS INTO THE EMPLOYEE TABLE 

 INSERT INTO [EMPLOYEES] ([EmployeeID],[FirstName],[LastName],[DepartmentID],[Position],[Salary])
 VALUES (1, 'JOHN', 'DOE', 1, 'MARKETING MANAGER', 120000.00),
         (2, 'JANE', 'SMITH', 2, 'FINANCIAL ANALYST', 95000.00),
		 (3, 'ROBERT', 'JOHNSON', 3, 'SOFTWARE ENGINEEER', 105000.00),
		 (4, 'EMILY', 'DAVIS', 1, 'SENIOR MARKETING STRATEGIST', 88000.00),
		 (5, 'MICHAEL', 'BROWN', 4, 'RISK ANALYST', 85000.00),
		 (6, 'SARAH', 'WILSON', 2, 'SENIOR ACCOUNTANT', 115000.00),
		 (7, 'DAVID', 'LEE', 3, 'SYSTEMS ARCHITECT', 125000.00),
		 (8, 'RACHEL', 'KIM', 5, 'SALES MANAGER', 110000.00),
		 (9, 'DANIEL', 'GREEN', 2, 'INVESTMENT MANAGER', 130000),
		 (10, 'ALEX', 'BAKER', 4, 'RISK MANAGEMENT CONSULTANT', 94000.00);

  
 -- I THEN CREATED THE DEPARTMENT TABLE

 CREATE TABLE DEPARTMENT
 (
  DepartmentID INT NOT NULL,
  DepartmentName VARCHAR (50) NOT NULL,
  );

  --DEPARTMENTID AS THE UNIQUE IDENTIFIER IN THE TABLE

   ALTER TABLE DEPARTMENT
 ADD CONSTRAINT PK_DEPARTMENT_DEPARTMENTID PRIMARY KEY (DEPARTMENTID);

 -- INSERTING RECORDS INTO THE TABLE

 INSERT INTO [DEPARTMENT] (DEPARTMENTID,DEPARTMENTNAME)
 VALUES (1, 'MARKETING'),
         (2, 'FINANCE'),
		 (3, 'ENGINEERNG'),
		 (4, 'RISK_MANAGEMENT'),
		 (5, 'SALES'); 

 
 -- I THEN CREATED THE INVESTMENT TABLE

 CREATE TABLE INVESTMENT
 (
  InvestmentID INT NOT NULL,
  InvestmentName VARCHAR (100) NOT NULL,
  InvestmentType VARCHAR (50) NOT NULL,
  DepartmentID INT NOT NULL,
  AmountInvested DECIMAL (15,2) NOT NULL,
  StartDate DATE NOT NULL,
  );

  -- INVESTMENTID AS THE UNIQUE IDENTIFIER IN THE TABLE

   ALTER TABLE INVESTMENT
 ADD CONSTRAINT PK_INVESTMENT_INVESTMENTID PRIMARY KEY (INVESTMENTID);  
 
 -- DEPARTMENTID IN THE INVESTMENT TABLE REFERENCING DEPARTMENTID IN THE DEPARTMENT TABLE (FOREIGN KEY)

 ALTER TABLE INVESTMENT
 ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENTID FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT (DEPARTMENTID);
 
 -- INSERTING RECORDS INTO THE TABLE

 INSERT INTO [INVESTMENT] ([InvestmentID],[InvestmentName],[InvestmentType],[DepartmentID],[AmountInvested],[StartDate])
 VALUES (1, 'SKYFUND ALPHA', 'EQUITY', 1, 2000000.00, '2025-01-10'),
        (2, 'SKYFUND BETA', 'BOND', 2, 1500000.00, '2025-02-01'),
		(3, 'SKYFUND DELTA', 'REAL ESTATE', 3, 3000000.00,'2025-03-01'),
		(4, 'SKYFUND OMEGA', 'STOCK', 4, 500000.00, '2025-01-20'),
		(5, 'SKYFUND GAMMA', 'REAL ESTATE', 2, 1200000.00, '2025-04-15'),
		(6, 'SKYFUND ZETA', 'BOND', 3, 25000000.00, '2025-02-28'),
		(7, 'SKYFUND THETA', 'EQUITY', 1, 3500000.00, '2025-03-10'),
		(8, 'SKYFUND KAPPA', 'REAL ESTATE', 4, 800000.00, '2025-04-05'),
		(9, 'SKYFUND IOTA', 'STOCK', 5, 2000000.00, '2025-05-01');

 
 -- SALARY ADJUSTMENT FOR EMPLOYEES WITH SALARY LESS THAN $100,000 IN THE EQUITY DEPARTMENT 

UPDATE E
SET E.[Salary] =  E.[Salary] * 1.15
FROM [EMPLOYEES] AS E
JOIN [DEPARTMENT] AS D 
ON E.DEPARTMENTID = D.DEPARTMENTID
JOIN [INVESTMENT] AS I
ON E.DEPARTMENTID = I.DEPARTMENTID
WHERE [InvestmentType] = 'EQUITY' AND [Salary] <100000;

-- DEPARTMENT CHANGE FOR EMPLOYEEID 4 FROM DEPARTMENT 1(MARKETING) TO 3(ENGINEERING)

UPDATE [EMPLOYEES]
SET DEPARTMENTID = 3
WHERE EMPLOYEEID = 4

-- 10% BONUS FOR EMPLOYEES IN THE RISK MANAGEMENT DEPARTMENT

UPDATE [EMPLOYEES]
SET PERFORMANCE_BONUS = SALARY * 0.10
WHERE [DepartmentID] = 4 

--- SALARY ADJUSTMENT FOR EMPLOYEEID 6

UPDATE [EMPLOYEES]
SET SALARY = 60000
WHERE EmployeeID = 6;

--INSERTING NEW EMPLOYEE RECORD TO THE EMPLOYEE TABLE

INSERT INTO [EMPLOYEES] ([EmployeeID],[FirstName],[LastName],[DepartmentID],[Position],[Salary])
VALUES (11, 'JOHN', 'THOMPSON', 1, 'SENIOR MARKETING STRATEGIST', 95000);

-- INSERTING NEW INVESTMENT RECORD INTO THE INVESTMENT TABLE. I CHANGED THE INVESTMENTID FROM6 TO 10 BRCAUSE WE ALREDY HAVE AN INESTMENTID 6

INSERT INTO [INVESTMENT] ([InvestmentID],[InvestmentName],[InvestmentType],[DepartmentID],[AmountInvested],[StartDate])
VALUES (10, 'SKYFUND X', 'REAL ESTATE', 3, 2000000, '2025-02-15');

---INSERTING MULTIPLE EMPLOYEE RECORD INTO THE EMPLOYEE TABLE

INSERT INTO [EMPLOYEES] ([EmployeeID],[FirstName],[LastName],[DepartmentID],[Position],[Salary])
VALUES (12, 'ALEX', 'BAKER', 2, 'SALES ASSOCIATE' , 70000),
       (13, 'RACHEL', 'KIM', 2, 'SENIOR RISK ANALYST', 85000),
	   (14, 'DANIEL', 'GREEN',2, 'RISK MANAGEMENT EXPERT', 90000);


--- INSERTING MULTIPLE INVESTMENT RECORDS INTO THE INVESTMENT TABLE

INSERT INTO [INVESTMENT] ([InvestmentID],[InvestmentName],[InvestmentType],[DepartmentID],[AmountInvested],[StartDate])
VALUES (11, 'SKYFUND Y', 'BOND', 2, 1500000, '2025-03-01'),
       (12, 'SKYFUNF Z','STOCK', 1, 800000, '2025-03-15'),
	   (13, 'SKYFUND W', 'REAL ESTATE',4, 3000000, '2025-04-01');

--- DELETING AN EMPLOYEE RECORD FROM THE EMPLOYEE TABLE

DELETE FROM [EMPLOYEES]
WHERE EMPLOYEEID = 10

-- DELETING DEPARTMENT 5 FROM THE DEPARTMENT TABLE WHILE MAINTAINING REFERENTIAL INTEGRITY 

UPDATE [EMPLOYEES]
SET [DepartmentID] = 1
WHERE [EmployeeID] = 8

UPDATE [INVESTMENT]
SET [DepartmentID] = 1
WHERE [InvestmentID] = 9

DELETE FROM [DEPARTMENT]
WHERE [DepartmentID] = 5

--- RETRIVING EMPLOYEE RECORDS WITH THEIR DEPARTMENT NAME 

SELECT E.[EmployeeID], E.[FirstName], E.[LastName], E.[Salary], D.[DepartmentID], D.[DepartmentName]
FROM [EMPLOYEES] AS E
INNER JOIN [DEPARTMENT] AS D
ON E.[DepartmentID] = D.[DepartmentID]


---- RETRIVING RECORDS OF EMPLOYEES WHOSE SALARY IS ABOVE $100,000

SELECT E.[FirstName], E.[LastName], D.[DepartmentName], E.[Salary]
FROM [EMPLOYEES] AS E
INNER JOIN [DEPARTMENT] AS D
ON E.[DepartmentID] = D.[DepartmentID]
WHERE SALARY > 100000


----RETRIVING HIGHEST PAID EMPLOYEE IN EACH DEPARTMENT

SELECT E.[FirstName], E.[LastName], D.[DepartmentName], E.[Salary]
FROM [EMPLOYEES] AS E
JOIN [DEPARTMENT] AS D
ON E.[DepartmentID] = D.[DepartmentID]
WHERE E.SALARY = (SELECT MAX([Salary]) FROM [EMPLOYEES]
WHERE [DepartmentID] = E.[DepartmentID]);


   SELECT *
 FROM [EMPLOYEES];

   SELECT *
  FROM [INVESTMENT];
  
  SELECT *
 FROM [DEPARTMENT];


